export const SET_INITIAL_DATA_SUCCESS = 'SET_INITIAL_DATA_SUCCESS';
export const SET_INITIAL_DATA_FAILURE = 'SET_INITIAL_DATA_FAILURE';
export const SET_INITIAL_DATA_REQUEST = 'SET_INITIAL_DATA_REQUEST';
