export const SET_CUSTOM_TEXT = 'SET_CUSTOM_TEXT';
export const VALIDATE_TEXT_LENGTH = 'VALIDATE_TEXT_LENGTH';
export const SET_MAX_TEXTAREA_HEIGHT = 'SET_MAX_TEXTAREA_HEIGHT';
export const SET_CURRENT_TEXTAREA_HEIGHT = 'SET_CURRENT_TEXTAREA_HEIGHT';
export const RESET_TEXT_CONTEXT = 'RESET_TEXT_CONTEXT';
