export const SET_NEW_ORDER_REQUEST = 'SET_NEW_ORDER_REQUEST';
export const SET_NEW_ORDER_SUCCESS = 'SET_NEW_ORDER_SUCCESS';
export const SET_NEW_ORDER_FAILED = 'SET_NEW_ORDER_FAILED';

export const SET_ORDER_REQUEST_PROGRESS = 'SET_ORDER_REQUEST_PROGRESS';
